[context.production.environment]
  REACT_APP_CHAIN_ID = "11155111"
  REACT_APP_ENABLE_HISTORY = "true"
  NODE_OPTIONS="--openssl-legacy-provider"

[context."staging".environment]
  REACT_APP_CHAIN_ID = "1"
  REACT_APP_ENABLE_HISTORY = "true"

[context."master".environment]
  REACT_APP_CHAIN_ID = "11155111"
  REACT_APP_ENABLE_HISTORY = "true"
  NODE_OPTIONS="--openssl-legacy-provider"

[context.branch-deploy]
  REACT_APP_CHAIN_ID = "11155111"
  REACT_APP_ENABLE_HISTORY = "true"

[context.deploy-preview.environment]
  REACT_APP_CHAIN_ID = "1"
  REACT_APP_ENABLE_HISTORY = "true"

[functions]
  directory = "packages/nouns-webapp/functions"

[build]
  command = "git submodule update --init --recursive --depth=1 && yarn workspace @nouns/webapp build"
  publish = "packages/nouns-webapp/build"
